-- TV2: đợt đăng ký và đề tài (kế thừa V1-V4 đã merge - không sửa file cũ)

CREATE TABLE registration_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    round_type VARCHAR(20) NOT NULL,
    gv_start TIMESTAMP NOT NULL,
    gv_end TIMESTAMP NOT NULL,
    sv_start TIMESTAMP NOT NULL,
    sv_end TIMESTAMP NOT NULL,
    gvpb_deadline TIMESTAMP,
    council_report_date TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_registration_periods_type CHECK (round_type IN ('MON_HOC', 'NCKH', 'TLCN', 'KLTN'))
);

CREATE TABLE topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(2000),
    status VARCHAR(20) NOT NULL,
    rejection_reason VARCHAR(500),
    round_id BIGINT NOT NULL REFERENCES registration_periods(id),
    department_id BIGINT NOT NULL REFERENCES departments(id),
    created_by_id BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_topics_status CHECK (status IN ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'PUBLISHED'))
);

CREATE TABLE topic_advisors (
    topic_id BIGINT NOT NULL REFERENCES topics(id),
    advisor_id BIGINT NOT NULL REFERENCES users(id),
    PRIMARY KEY (topic_id, advisor_id)
);

CREATE INDEX idx_topics_round ON topics(round_id);
CREATE INDEX idx_topics_department ON topics(department_id);
CREATE INDEX idx_topics_status ON topics(status);
CREATE INDEX idx_topics_created_by ON topics(created_by_id);